name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2026-06-05"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow-db"
database_id = "e9034147-eb11-4777-944b-717731932b81"
